// <auto-generated />
using System;
using CSharpAPI.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CSharp_Parking_API.Migrations
{
    [DbContext(typeof(SQLite_Database))]
    [Migration("20251030115143_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.9");

            modelBuilder.Entity("CSharpAPI.Models.M_Parkinglots", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("address")
                        .HasColumnType("TEXT");

                    b.Property<int>("capacity")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("TEXT");

                    b.Property<float>("daytarriff")
                        .HasColumnType("REAL");

                    b.Property<string>("location")
                        .HasColumnType("TEXT");

                    b.Property<string>("name")
                        .HasColumnType("TEXT");

                    b.Property<int>("reserved")
                        .HasColumnType("INTEGER");

                    b.HasKey("id");

                    b.ToTable("Parkinglots");
                });

            modelBuilder.Entity("CSharpAPI.Models.M_Payments", b =>
                {
                    b.Property<Guid>("hash")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<float>("amount")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("completed")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("TEXT");

                    b.Property<string>("initiator")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("parking_lot_id")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("session_id")
                        .HasColumnType("TEXT");

                    b.Property<string>("transactions")
                        .HasColumnType("TEXT");

                    b.HasKey("hash");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("CSharpAPI.Models.M_Reservations", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<float>("cost")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("end_time")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("parking_lot_id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("start_time")
                        .HasColumnType("TEXT");

                    b.Property<int>("status")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("user_id")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("vehicle_id")
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.ToTable("Reservations");
                });

            modelBuilder.Entity("CSharpAPI.Models.M_Session", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<float>("cost")
                        .HasColumnType("REAL");

                    b.Property<int>("duration_minutes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("license_plate")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("parking_lot_id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("started")
                        .HasColumnType("TEXT");

                    b.Property<int>("status")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("stopped")
                        .HasColumnType("TEXT");

                    b.Property<string>("user")
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.ToTable("Sessions");
                });

            modelBuilder.Entity("CSharpAPI.Models.M_Users", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("active")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("birth_year")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("TEXT");

                    b.Property<string>("email")
                        .HasColumnType("TEXT");

                    b.Property<string>("name")
                        .HasColumnType("TEXT");

                    b.Property<string>("password")
                        .HasColumnType("TEXT");

                    b.Property<string>("phone")
                        .HasColumnType("TEXT");

                    b.Property<int>("role")
                        .HasColumnType("INTEGER");

                    b.Property<string>("username")
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("CSharpAPI.Models.M_Vehicles", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("color")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("TEXT");

                    b.Property<string>("license_plate")
                        .HasColumnType("TEXT");

                    b.Property<string>("make")
                        .HasColumnType("TEXT");

                    b.Property<string>("model")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("user_id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("year")
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.ToTable("Vehicles");
                });

            modelBuilder.Entity("CSharpAPI.Models.M_Parkinglots", b =>
                {
                    b.OwnsOne("CSharpAPI.Models.Coordinates", "coordinates", b1 =>
                        {
                            b1.Property<Guid>("M_Parkinglotsid")
                                .HasColumnType("TEXT");

                            b1.Property<float>("lat")
                                .HasColumnType("REAL");

                            b1.Property<float>("lng")
                                .HasColumnType("REAL");

                            b1.HasKey("M_Parkinglotsid");

                            b1.ToTable("Parkinglots");

                            b1.WithOwner()
                                .HasForeignKey("M_Parkinglotsid");
                        });

                    b.Navigation("coordinates");
                });

            modelBuilder.Entity("CSharpAPI.Models.M_Payments", b =>
                {
                    b.OwnsOne("CSharpAPI.Models.T_Data", "t_data", b1 =>
                        {
                            b1.Property<Guid>("M_Paymentshash")
                                .HasColumnType("TEXT");

                            b1.Property<float>("amount")
                                .HasColumnType("REAL");

                            b1.Property<string>("bank")
                                .HasColumnType("TEXT");

                            b1.Property<DateTime>("date")
                                .HasColumnType("TEXT");

                            b1.Property<string>("issuer")
                                .HasColumnType("TEXT");

                            b1.Property<string>("method")
                                .HasColumnType("TEXT");

                            b1.HasKey("M_Paymentshash");

                            b1.ToTable("Payments");

                            b1.WithOwner()
                                .HasForeignKey("M_Paymentshash");
                        });

                    b.Navigation("t_data");
                });
#pragma warning restore 612, 618
        }
    }
}
