// <auto-generated />
using System;
using CSharpAPI.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CSharp_Parking_API.Migrations
{
    [DbContext(typeof(SQLite_Database))]
    [Migration("20260109210806_UpdateModel")]
    partial class UpdateModel
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.9");

            modelBuilder.Entity("CSharpAPI.Models.M_BalanceTransaction", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("amount")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("balance_id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("TEXT");

                    b.Property<string>("currency")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("description")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("payment_id")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("session_id")
                        .HasColumnType("TEXT");

                    b.Property<int>("type")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("user_id")
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.ToTable("BalanceTransactions");
                });

            modelBuilder.Entity("CSharpAPI.Models.M_Billing", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("amount")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("TEXT");

                    b.Property<string>("currency")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("description")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("due_date")
                        .HasColumnType("TEXT");

                    b.Property<string>("invoice_number")
                        .HasColumnType("TEXT");

                    b.Property<bool>("paid")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("paid_at")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("payment_id")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("reservation_id")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("session_id")
                        .HasColumnType("TEXT");

                    b.Property<int>("status")
                        .HasColumnType("INTEGER");

                    b.Property<int>("type")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("user_id")
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.ToTable("Billing");
                });

            modelBuilder.Entity("CSharpAPI.Models.M_Company", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("active")
                        .HasColumnType("INTEGER");

                    b.Property<string>("address")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("TEXT");

                    b.Property<string>("email")
                        .HasColumnType("TEXT");

                    b.Property<bool>("monthly_billing_enabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("phone")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("primary_contact_user_id")
                        .HasColumnType("TEXT");

                    b.Property<string>("tax_id")
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.ToTable("Companies");
                });

            modelBuilder.Entity("CSharpAPI.Models.M_CompanyUser", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("company_id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("joined_at")
                        .HasColumnType("TEXT");

                    b.Property<int>("role")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("user_id")
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.ToTable("CompanyUsers");
                });

            modelBuilder.Entity("CSharpAPI.Models.M_Hotel", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("active")
                        .HasColumnType("INTEGER");

                    b.Property<string>("address")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("discount_percentage")
                        .HasColumnType("TEXT");

                    b.Property<string>("email")
                        .HasColumnType("TEXT");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("phone")
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.ToTable("Hotels");
                });

            modelBuilder.Entity("CSharpAPI.Models.M_HotelGuest", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("check_in")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("check_out")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("TEXT");

                    b.Property<bool>("discount_applied")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("hotel_id")
                        .HasColumnType("TEXT");

                    b.Property<string>("reservation_number")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("user_id")
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.ToTable("HotelGuests");
                });

            modelBuilder.Entity("CSharpAPI.Models.M_Parkinglots", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("address")
                        .HasColumnType("TEXT");

                    b.Property<int>("capacity")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("TEXT");

                    b.Property<float>("daytarriff")
                        .HasColumnType("REAL");

                    b.Property<string>("location")
                        .HasColumnType("TEXT");

                    b.Property<string>("name")
                        .HasColumnType("TEXT");

                    b.Property<int>("reserved")
                        .HasColumnType("INTEGER");

                    b.HasKey("id");

                    b.ToTable("Parkinglots");
                });

            modelBuilder.Entity("CSharpAPI.Models.M_Payments", b =>
                {
                    b.Property<Guid>("hash")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<float>("amount")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("completed")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("id")
                        .HasColumnType("TEXT");

                    b.Property<string>("initiator")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("paid_at")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("parking_lot_id")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("reservation_id")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("session_id")
                        .HasColumnType("TEXT");

                    b.Property<string>("transactions")
                        .HasColumnType("TEXT");

                    b.HasKey("hash");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("CSharpAPI.Models.M_Reservations", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<float>("cost")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("end_time")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("parking_lot_id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("start_time")
                        .HasColumnType("TEXT");

                    b.Property<int>("status")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("user_id")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("vehicle_id")
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.HasIndex("parking_lot_id");

                    b.HasIndex("user_id");

                    b.HasIndex("vehicle_id");

                    b.ToTable("Reservations");
                });

            modelBuilder.Entity("CSharpAPI.Models.M_RevokedTokens", b =>
                {
                    b.Property<string>("TokenId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("RevokedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("TokenId");

                    b.ToTable("RevokedTokens");
                });

            modelBuilder.Entity("CSharpAPI.Models.M_Session", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<float>("cost")
                        .HasColumnType("REAL");

                    b.Property<int>("duration_minutes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("license_plate")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("parking_lot_id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("started")
                        .HasColumnType("TEXT");

                    b.Property<int>("status")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("stopped")
                        .HasColumnType("TEXT");

                    b.Property<string>("user")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("vehicle_id")
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.HasIndex("parking_lot_id");

                    b.HasIndex("vehicle_id");

                    b.ToTable("Sessions");
                });

            modelBuilder.Entity("CSharpAPI.Models.M_UserBalance", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("balance")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("TEXT");

                    b.Property<string>("currency")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("last_updated")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("user_id")
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.ToTable("UserBalances");
                });

            modelBuilder.Entity("CSharpAPI.Models.M_Users", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("active")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("birth_year")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("TEXT");

                    b.Property<string>("email")
                        .HasColumnType("TEXT");

                    b.Property<string>("name")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("parking_lot_id")
                        .HasColumnType("TEXT");

                    b.Property<string>("password")
                        .HasColumnType("TEXT");

                    b.Property<string>("phone")
                        .HasColumnType("TEXT");

                    b.Property<int>("role")
                        .HasColumnType("INTEGER");

                    b.Property<string>("username")
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("CSharpAPI.Models.M_Vehicles", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("color")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("TEXT");

                    b.Property<string>("license_plate")
                        .HasColumnType("TEXT");

                    b.Property<string>("make")
                        .HasColumnType("TEXT");

                    b.Property<string>("model")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("user_id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("year")
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.HasIndex("user_id");

                    b.ToTable("Vehicles");
                });

            modelBuilder.Entity("CSharpAPI.Models.M_Parkinglots", b =>
                {
                    b.OwnsOne("CSharpAPI.Models.Coordinates", "coordinates", b1 =>
                        {
                            b1.Property<Guid>("M_Parkinglotsid")
                                .HasColumnType("TEXT");

                            b1.Property<float>("lat")
                                .HasColumnType("REAL");

                            b1.Property<float>("lng")
                                .HasColumnType("REAL");

                            b1.HasKey("M_Parkinglotsid");

                            b1.ToTable("Parkinglots");

                            b1.WithOwner()
                                .HasForeignKey("M_Parkinglotsid");
                        });

                    b.Navigation("coordinates");
                });

            modelBuilder.Entity("CSharpAPI.Models.M_Payments", b =>
                {
                    b.OwnsOne("CSharpAPI.Models.T_Data", "t_data", b1 =>
                        {
                            b1.Property<Guid>("M_Paymentshash")
                                .HasColumnType("TEXT");

                            b1.Property<float>("amount")
                                .HasColumnType("REAL");

                            b1.Property<string>("bank")
                                .HasColumnType("TEXT");

                            b1.Property<DateTime>("date")
                                .HasColumnType("TEXT");

                            b1.Property<string>("issuer")
                                .HasColumnType("TEXT");

                            b1.Property<string>("method")
                                .HasColumnType("TEXT");

                            b1.HasKey("M_Paymentshash");

                            b1.ToTable("Payments");

                            b1.WithOwner()
                                .HasForeignKey("M_Paymentshash");
                        });

                    b.Navigation("t_data");
                });

            modelBuilder.Entity("CSharpAPI.Models.M_Reservations", b =>
                {
                    b.HasOne("CSharpAPI.Models.M_Parkinglots", "parking_lot")
                        .WithMany()
                        .HasForeignKey("parking_lot_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CSharpAPI.Models.M_Users", "user")
                        .WithMany()
                        .HasForeignKey("user_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CSharpAPI.Models.M_Vehicles", "vehicle")
                        .WithMany()
                        .HasForeignKey("vehicle_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("parking_lot");

                    b.Navigation("user");

                    b.Navigation("vehicle");
                });

            modelBuilder.Entity("CSharpAPI.Models.M_Session", b =>
                {
                    b.HasOne("CSharpAPI.Models.M_Parkinglots", "parking_lot")
                        .WithMany()
                        .HasForeignKey("parking_lot_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CSharpAPI.Models.M_Vehicles", "vehicle_license_plate")
                        .WithMany()
                        .HasForeignKey("vehicle_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("parking_lot");

                    b.Navigation("vehicle_license_plate");
                });

            modelBuilder.Entity("CSharpAPI.Models.M_Vehicles", b =>
                {
                    b.HasOne("CSharpAPI.Models.M_Users", "M_Users")
                        .WithMany()
                        .HasForeignKey("user_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("M_Users");
                });
#pragma warning restore 612, 618
        }
    }
}
